--Tasks to be performed:
--1. Display the number of states present in the LocationTable.
select COUNT(DISTINCT STATE) FROM LOCATION

--2. How many products are of regular type?
SELECT count(*) from product
where Type = 'regular';

--3. How much spending has been done on marketing of product ID 1?
select productid, SUM(marketing) as tot_marketing from fact
where ProductId=1
group by productid

--4. What is the minimum sales of a product?
select productid,MIN(sales) as minimumsales from fact
group by ProductId
order by minimumsales asc

--5. Display the max Cost of Good Sold (COGS).
select Productid,MAX(cogs) as max_cogs from fact
group by ProductId
order by max_cogs desc


--6. Display the details of the product where product type is coffee.
select * from product where product_type = 'coffee' 
select * from fact
select * from product

--7. Display the details where total expenses are greater than 40.
select * from fact f inner join product p ON f.productid=p.productid
where total_expenses > 40

--8. What is the average sales in area code 719?
select area_code, avg(sales) as avgsales from fact
where area_code= 719
group by area_code

--9. Find out the total profit generated by Colorado state.
select SUM(profit) as tot_profit_colorado from fact f
inner join Location L on f.Area_Code = L.Area_Code
where State = 'colorado'

--10. Display the average inventory for each product ID.
select productid, avg(inventory) as avg_inventory from fact
group by productid
order by productid asc

--11. Display state in a sequential order in a Location Table.
select distinct(state), area_code from location
order by state

--12. Display the average budget of the Product where the average budget
--margin should be greater than 100.
select productid,avg( budget_margin) as avgbudget from fact
group by productid
having avg(budget_margin) >100


--13. What is the total sales done on date 2010-01-01?

select date, sum(sales) as sumsales from fact
where date ='2010-01-01'
group by date


--14. Display the average total expense of each product ID on an individual date.
select productid,date, avg(total_expenses) as avg_expenses from fact
group by  productid, date
order by date, productid

--15. Display the table with the following attributes such as date, productID,
--product_type, product, sales, profit, state, area_code.
select f.date,f.productid,p.product_type,
p.product, f.sales,f.area_code, L.state,
f.profit from fact f inner join location l on f.area_code=l.area_code
inner join product p on f.productid= p.productid


--16. Display the rank without any gap to show the sales wise rank.
select sales, dense_rank() over( partition by productid order by sales desc) from fact;

--17. Find the state wise profit and sales.
select state, sum(profit) as tot_profit, sum(sales) as tot_sales from fact
 inner join location on fact.area_code=location.area_code
 group by state
 order by state

--18. Find the state wise profit and sales along with the product name.
select state, sum(profit) as tot_profit, sum (sales) as tot_sales,
product.product from fact inner join product on fact.productid=product.productid
inner join location on fact.area_code= location.area_code
group by state, product
order by state

--19. If there is an increase in sales of 5%, calculate the increasedsales.
select sales, (1.05*sales) as increasedsales from fact;

--20. Find the maximum profit along with the product ID and producttype.
select product.productid, product_type,PROFIT
FROM FACT INNER JOIN PRODUCT ON FACT.PRODUCTID=PRODUCT.PRODUCTID
WHERE fact.PROFIT = (select MAX(PROFIT) FROM FACT)


--21. Create a stored procedure to fetch the result according to the product type
--from Product Table.
create procedure sp_pr (@prtype varchar(32))
as
begin
select * from product where product_type=@prtype;
end;

exec sp_pr 'coffee'
exec sp_pr tea

--22. Write a query by creating a condition in which if the total expenses is less than
--60 then it is a profit or else loss.
select productid, 
(case when total_expenses > 60 then 'profit' else 'lose' end) 
as lose_profit from fact

--23. Give the total weekly sales value with the date and product ID details. Use
--roll-up to pull the data in hierarchical order.
select DATEPART(WEEK,Date) as week,sum(sales), productid from fact
group by rollup (DATEPART(week,date),productid)
order by datepart(week,date)


--24. Apply union and intersection operator on the tables which consist of
--attribute area code.
select  area_code from fact 
union
select Area_Code from location   
order by area_code

select  area_code from fact 
intersect
select Area_Code from location   
order by area_code

--25.Create a user-defined function for the product table to fetch a particular
--product type based upon the user’s preference.

 create or alter function fn_1 (@productid int)
 returns table
as
return
(select product_type,Productid  from Product where Productid = @productid);

select * from dbo.[fn_1] (3);

--26. Change the product type from coffee to tea where product ID is 1 and undo it.
 begin transaction
 update Product set Product_type = replace(Product_type,'coffee','tea')
 where ProductId=1;
 rollback transaction
--27. Display the date, product ID and sales where total expenses are
--between 100 to 200.
select DATE, productid, sales from fact where Total_Expenses between 100 and 200;

--28. Delete the records in the Product Table for regular type.
delete from product where type = 'regular'

--29. Display the ASCII value of the fifth character from the columnProduct.
select ascii(substring(product, 5,1)) from product



select* from fact
select* from location
select* from product

select * from fact where Area_Code =203




